FROM buildpack-deps:%%VERSION%%

RUN DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install \
  ruby \
  ruby-dev \
  unzip \
&& rm -rf /var/lib/apt/lists/*

RUN gem install fpm fpm-cookery --no-rdoc --no-ri

ARG BUILD_DATE
ARG VCS_REF
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url="https://github.com/dpirotte/docker-fpm-cookery" \
      org.label-schema.schema-version="1.0"
