#!/bin/bash

sed "s/%%VERSION%%/$IMAGE_TAG/" Dockerfile.template \
| docker build \
  --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
  -t $DOCKER_REPO:$IMAGE_TAG -
